### ISSUE TITLE
Little Suggestion

### ISSUE THREAD

**Issue by CarryLambo** [Exodus-20-2/Lucid#7]
Hi!, i like this sniper works great but can u add to use sniper on some alts and the nitro sniped wil redeem in 1 main account?

Like put many tokens to snipe and the main account will have the nitro

the rest very good sniper

**Comment by Exodus-20-2** [comment]
Sure, thanks for the suggestions.

**Comment by ninjaw-art** [comment]
so how do i like actually use it

**Comment by Exodus-20-2** [comment]
@ninjaw-art How do you actually use what?
