### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by reddythedev** [Exodus-20-2/Lucid#8]
Iss there possible way how to download exe file? When i click "Download here" it say that site doesn' exist.

**Comment by Exodus-20-2** [comment]
I haven't released a compiled exe yet, i will do that now

**Comment by reddythedev** [comment]
Also, when i use guild joiner it says that this command hasn't been made yet, is this right?

**Comment by Exodus-20-2** [comment]
Yeah the command hasn't been properly made yet, I plan on making that next update

**Comment by reddythedev** [comment]
Okay that's all, thanks for fast response!
